### ISSUE TITLE
Z-normalize data

### ISSUE THREAD

**Issue by muthissar** [intelligenttrafficforecasting/busmodders#8]

**Comment by muthissar** [comment]
We probably need to load all data (test and train) and compute the mean std for that (preferebly store it such that we don't compute it each time we run the code)

**Comment by jeppe742** [comment]
Created a Dataset class that loads the data, which can be used to normalize the data by the following:

```python
train = MoviaBusDataset('data/train')
test = MoviaBusDataset('data/test')

train.normalize()
# mean and standard deviation is stored in train object,
# so we can use them when we want to normalize the test set
test.normalize(train.mean, train.std)


```
